# Gaming Profiles 2025 (Steam, PlayStation, Xbox)
![image.png](logo/logo_xbox_steam_playstation.png)

## Problématique

Quels sont les facteurs qui influencent le succès global d’un jeu vidéo?

## Import des librairies

In [3]:
import pandas as pd
import math
import numbers

## 1) Exploration des datasets

In [4]:
df_achievements_playstation = pd.read_csv("playstation/achievements.csv")
df_achievements_playstation.head()

,achievementid,gameid,title,description,rarity
0,749980_6103480,749980,Platinum Cup,Get all the trophies,Platinum
1,749980_6103481,749980,Arcade Beginner,Finish race,Bronze
2,749980_6103482,749980,Arcade Beginner Dirt,Finish race,Bronze
3,749980_6103483,749980,Arcade Intermediate,Finish race,Silver
4,749980_6103484,749980,Arcade Advanced,Finish race,Silver

In [5]:
print("df_achievements_playstation shape")
print(df_achievements_playstation.shape)

print()

print("df_achievements_playstation info")
print(df_achievements_playstation.info())
print()

print("df_achievements_playstation describe")
df_achievements_playstation.describe(include='all')

print()
print("df_achievements_playstation nombre de valeur manquante par colonne")
print(df_achievements_playstation.isnull().sum())

df_achievements_playstation shape
(846563, 5)

df_achievements_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846563 entries, 0 to 846562
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   achievementid  846563 non-null  object
 1   gameid         846563 non-null  int64
 2   title          846559 non-null  object
 3   description    846547 non-null  object
 4   rarity         846563 non-null  object
dtypes: int64(1), object(4)
memory usage: 32.3+ MB
None

df_achievements_playstation describe

df_achievements_playstation nombre de valeur manquante par colonne
achievementid     0
gameid            0
title             4
description      16
rarity            0
dtype: int64

In [6]:
df_achievements_playstation['rarity'].value_counts()

rarity
Bronze      437484
Silver      210840
Gold        172650
Platinum     25589
Name: count, dtype: int64

In [7]:
df_games_playstation = pd.read_csv("playstation/games.csv")
df_games_playstation.head()

,gameid,title,platform,developers,publishers,genres,supported_languages,release_date
0,749375,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22
1,749839,Sunforge Solar Survival,PS4,['GrizzlyGames'],['GrizzlyGames'],NaN,NaN,2024-11-21
2,749347,Find Love Or Die Trying,PS5,['Sunseeker Games'],['Ratalaika Games'],['Visual Novel'],NaN,2024-11-22
3,749341,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22
4,749097,Bust A Block 2,PS5,['ThiGames'],['ThiGames'],['Puzzle'],NaN,2024-11-21

In [8]:
print("df_games_playstation shape")
print(df_games_playstation.shape)

print()

print("df_games_playstation info")
print(df_games_playstation.info())
print()

print("df_games_playstation describe")
df_games_playstation.describe(include='all')

print()

print("df_games_playstation nombre de valeur manquante par colonne")
print(df_games_playstation.isnull().sum())

df_games_playstation shape
(23151, 8)

df_games_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23151 entries, 0 to 23150
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gameid               23151 non-null  int64
 1   title                23151 non-null  object
 2   platform             23151 non-null  object
 3   developers           23134 non-null  object
 4   publishers           23140 non-null  object
 5   genres               23009 non-null  object
 6   supported_languages  10614 non-null  object
 7   release_date         23151 non-null  object
dtypes: int64(1), object(7)
memory usage: 1.4+ MB
None

df_games_playstation describe

df_games_playstation nombre de valeur manquante par colonne
gameid                     0
title                      0
platform                   0
developers                17
publishers                11
genres                   142
supported_languages    12537
release_date               0
dtype: int64

        la langue est manquante sur 54% des données on peut ne pas garder cette colonne, il faut changer le format des colonnes et récuperer les données des colonnes developers, publishers et genres qui sont des listes avec des lambda

In [9]:
df_history_playstation = pd.read_csv("playstation/history.csv")
df_history_playstation.head()

   playerid   achievementid        date_acquired
0   1911732  670209_5436079  2024-11-28 10:23:24
1   1911732  670209_5436078  2024-11-28 09:36:41
2   1911732  670209_5436077  2024-11-28 08:31:54
3   1911732  670209_5436076  2024-11-28 08:19:23
4   1911732  658551_5368954  2024-10-05 13:12:35

In [10]:
print("df_history_playstation shape")
print(df_history_playstation.shape)

print()

print("df_history_playstation info")
print(df_history_playstation.info())
print()

print("df_history_playstation describe")
df_history_playstation.describe(include='all')

print()

print("df_history_playstation nombre de valeur manquante par colonne")
print(df_history_playstation.isnull().sum())

df_history_playstation shape
(19510083, 3)

df_history_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19510083 entries, 0 to 19510082
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   playerid       int64
 1   achievementid  object
 2   date_acquired  object
dtypes: int64(1), object(2)
memory usage: 446.6+ MB
None

df_history_playstation describe

df_history_playstation nombre de valeur manquante par colonne
playerid         0
achievementid    0
date_acquired    0
dtype: int64

In [11]:
df_players_playstation = pd.read_csv("playstation/players.csv")
df_players_playstation.head()

   playerid         nickname             country
0   2744567  ieizazuBisnorog             Croatia
1    328452     DiscoGitaroo       United States
2   2521482          Ectivey      United Kingdom
3    390175      Tomie_Again  Korea, Republic of
4   4348945     Lordhell1986  Russian Federation

In [12]:
print("df_players_playstation shape")
print(df_players_playstation.shape)

print()

print("df_players_playstation info")
print(df_players_playstation.info())
print()

print("df_players_playstation describe")
df_players_playstation.describe(include='all')

print()

print("df_players_playstation nombre de valeur manquante par colonne")
print(df_players_playstation.isnull().sum())

df_players_playstation shape
(356600, 3)

df_players_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356600 entries, 0 to 356599
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  356600 non-null  int64
 1   nickname  356600 non-null  object
 2   country   356600 non-null  object
dtypes: int64(1), object(2)
memory usage: 8.2+ MB
None

df_players_playstation describe

df_players_playstation nombre de valeur manquante par colonne
playerid    0
nickname    0
country     0
dtype: int64

In [13]:
df_prices_playstation = pd.read_csv("playstation/prices.csv")
df_prices_playstation.head()

   gameid    usd    eur    gbp     jpy     rub date_acquired
0  749347  10.39  10.39   7.99  1408.0   929.0    2025-02-22
1  749281   1.49   1.49   1.19   220.0     NaN    2025-02-22
2  749839  14.99  14.99  11.99  2310.0  1069.0    2025-02-22
3  749280   1.49   1.49   1.19   220.0     NaN    2025-02-22
4  749375   0.99   0.49   0.39   165.0    71.0    2025-02-22

In [14]:
print("df_prices_playstation shape")
print(df_prices_playstation.shape)

print()

print("df_prices_playstation info")
print(df_prices_playstation.info())
print()

print("df_prices_playstation describe")
df_prices_playstation.describe(include='all')

print()

print("df_prices_playstation nombre de valeur manquante par colonne")
print(df_prices_playstation.isnull().sum())

df_prices_playstation shape
(62816, 7)

df_prices_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62816 entries, 0 to 62815
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gameid         62816 non-null  int64
 1   usd            49251 non-null  float64
 2   eur            47264 non-null  float64
 3   gbp            48637 non-null  float64
 4   jpy            27038 non-null  float64
 5   rub            10911 non-null  float64
 6   date_acquired  62816 non-null  object
dtypes: float64(5), int64(1), object(1)
memory usage: 3.4+ MB
None

df_prices_playstation describe

df_prices_playstation nombre de valeur manquante par colonne
gameid               0
usd              13565
eur              15552
gbp              14179
jpy              35778
rub              51905
date_acquired        0
dtype: int64

In [15]:
df_prices_playstation.isnull().sum()

gameid               0
usd              13565
eur              15552
gbp              14179
jpy              35778
rub              51905
date_acquired        0
dtype: int64

        modifier le format de la colonne date_acquired, le prix en usd n'est pas renseigné sur 22% des lignes, le prix en euros n'est pas renseigné sur 24% des lignes, le prix en gbp n'est pas renseigné sur 22% des lignes, le prix en jby n'est pas renseigné sur 57% des lignes, le prix en rub n'est pas renseigné sur 83% des lignes

In [16]:
df_purchased_games_playstation = pd.read_csv("playstation/purchased_games.csv")
df_purchased_games_playstation.head()

   playerid                                            library
0    268071  [14972, 417905, 14693, 7742, 20162, 461983, 12...
1   2218485  [410618, 17456, 16034, 138931, 175202, 331007,...
2    253885  [417808, 706747, 619583, 492711, 555631, 18167...
3   1911732  [670209, 694794, 658551, 582894, 602666, 65531...
4   3098524  [19362, 170350, 12653, 20230, 12750, 18141, 41...

In [17]:
print("df_purchased_games_playstation shape")
print(df_purchased_games_playstation.shape)

print()

print("df_purchased_games_playstation info")
print(df_purchased_games_playstation.info())
print()

print("df_purchased_games_playstation describe")
df_purchased_games_playstation.describe(include='all')

print()

print("df_purchased_games_playstation nombre de valeur manquante par colonne")
print(df_purchased_games_playstation.isnull().sum())

df_purchased_games_playstation shape
(46582, 2)

df_purchased_games_playstation info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46582 entries, 0 to 46581
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   playerid  46582 non-null  int64
 1   library   46582 non-null  object
dtypes: int64(1), object(1)
memory usage: 728.0+ KB
None

df_purchased_games_playstation describe

df_purchased_games_playstation nombre de valeur manquante par colonne
playerid    0
library     0
dtype: int64

        Convertir la colonne library qui est une liste avec une lambda

In [18]:
df_achievements_steam = pd.read_csv("steam/achievements.csv")
df_achievements_steam.head()

,achievementid,gameid,title,description
0,2621440_ACH_FIRST_KILL,2621440,FIRST KILL,You should kill ONE enemy.
1,2621440_ACH_0_LEVEL_COMPLETED,2621440,TUTORIAL COMPLETED,You should complete tutorial.
2,2621440_ACH_1_LEVEL_COMPLETED,2621440,FIRST LEVEL,You should complete first level
3,2621440_ACH_2_LEVEL_COMPLETED,2621440,SECOND LEVEL,You should complete second level
4,2621440_ACH_3_LEVEL_COMPLETED,2621440,THIRD LEVEL,You should complete third level

In [19]:
print("df_achievements_steam shape")
print(df_achievements_steam.shape)

print()

print("df_achievements_steam info")
print(df_achievements_steam.info())
print()

print("df_achievements_steam describe")
df_achievements_steam.describe(include='all')

print()

print("df_achievements_steam nombre de valeur manquante par colonne")
print(df_achievements_steam.isnull().sum())

df_achievements_steam shape
(1939027, 4)

df_achievements_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1939027 entries, 0 to 1939026
Data columns (total 4 columns):
 #   Column         Dtype
---  ------         -----
 0   achievementid  object
 1   gameid         int64
 2   title          object
 3   description    object
dtypes: int64(1), object(3)
memory usage: 59.2+ MB
None

df_achievements_steam describe

df_achievements_steam nombre de valeur manquante par colonne
achievementid         0
gameid                0
title              4471
description      172212
dtype: int64

In [20]:
df_achievements_steam_title_null = df_achievements_steam[df_achievements_steam['title'].isna()]
df_achievements_steam_title_null

                        achievementid   gameid title               description
41551          792670_ACH_DEATH_ANNIE   792670   NaN  Get killed by the killer
145239    806160_NEW_ACHIEVEMENT_3_22   806160   NaN      Carrots collected: 9
145307    806160_NEW_ACHIEVEMENT_3_23   806160   NaN     Carrots collected: 10
145656    806160_NEW_ACHIEVEMENT_3_20   806160   NaN      Carrots collected: 7
145802    806160_NEW_ACHIEVEMENT_3_21   806160   NaN      Carrots collected: 8
...                               ...      ...   ...                       ...
1646882  2206130_NEW_ACHIEVEMENT_1_26  2206130   NaN                       NaN
1646883  2206130_NEW_ACHIEVEMENT_1_27  2206130   NaN                       NaN
1646884  2206130_NEW_ACHIEVEMENT_1_28  2206130   NaN                       NaN
1646885  2206130_NEW_ACHIEVEMENT_1_29  2206130   NaN                       NaN
1846369      1304420_ACHIEVEMENT_NULL  1304420   NaN    ACHIEVEMENT NOT FOUND.

[4471 rows x 4 columns]

        Ne pas prendre la colonne description

In [21]:
df_friends_steam = pd.read_csv("steam/friends.csv")
df_friends_steam.head()

            playerid                                            friends
0  76561198060422271  ['76561198018120276', '76561198034545417', '76...
1  76561198113439786  ['76561198047435192', '76561198059136488', '76...
2  76561198149851326  ['76561197991555589', '76561198003513187', '76...
3  76561198296997371                                                NaN
4  76561198895573082  ['76561197960300358', '76561197961330830', '76...

In [22]:
print("df_friends_steam shape")
print(df_friends_steam.shape)

print()

print("df_friends_steam info")
print(df_friends_steam.info())
print()

print("df_friends_steam describe")
df_friends_steam.describe(include='all')

print()

print("df_friends_steam nombre de valeur manquante par colonne")
print(df_friends_steam.isnull().sum())

df_friends_steam shape
(424683, 2)

df_friends_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424683 entries, 0 to 424682
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  424683 non-null  int64
 1   friends   339461 non-null  object
dtypes: int64(1), object(1)
memory usage: 6.5+ MB
None

df_friends_steam describe

df_friends_steam nombre de valeur manquante par colonne
playerid        0
friends     85222
dtype: int64

        Il y a 20% de ligne de la colonne friends qui sont vide

In [23]:
df_games_steam = pd.read_csv("steam/games.csv")
df_games_steam.head()

,gameid,title,developers,publishers,genres,supported_languages,release_date
0,3281560,Horror Game To Play With Friends! Playtest,NaN,NaN,NaN,NaN,2024-10-21
1,3280930,Eternals' Path Playtest,NaN,NaN,NaN,NaN,2024-10-17
2,3280770,ANGST: A TALE OF SURVIVAL - Singleplayer Playtest,NaN,NaN,NaN,NaN,2024-10-13
3,3279790,Montabi Playtest,NaN,NaN,NaN,NaN,2024-10-13
4,3278320,파이팅걸 유리 Playtest,NaN,NaN,NaN,NaN,2024-10-12

In [24]:
print("df_games_steam shape")
print(df_games_steam.shape)

print()

print("df_games_steam info")
print(df_games_steam.info())
print()

print("df_games_steam describe")
df_games_steam.describe(include='all')

print()

print("df_games_steam nombre de valeur manquante par colonne")
print(df_games_steam.isnull().sum())

df_games_steam shape
(98248, 7)

df_games_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98248 entries, 0 to 98247
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gameid               98248 non-null  int64
 1   title                98245 non-null  object
 2   developers           92689 non-null  object
 3   publishers           92307 non-null  object
 4   genres               92699 non-null  object
 5   supported_languages  92742 non-null  object
 6   release_date         98248 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.2+ MB
None

df_games_steam describe

df_games_steam nombre de valeur manquante par colonne
gameid                    0
title                     3
developers             5559
publishers             5941
genres                 5549
supported_languages    5506
release_date              0
dtype: int64

In [25]:
print("df_games_steam nombre de valeur manquante par colonne")
print(df_games_steam.isnull().sum())

df_games_steam nombre de valeur manquante par colonne
gameid                    0
title                     3
developers             5559
publishers             5941
genres                 5549
supported_languages    5506
release_date              0
dtype: int64

        Il y a à peu preès 5% des lignes developerss, publishers et genres qui sont vides

In [26]:
df_history_steam = pd.read_csv("steam/history.csv")
df_history_steam.head()

            playerid achievementid        date_acquired
0  76561198220441373  403640_ACH_1  2019-12-18 15:33:43
1  76561198220441373  403640_ACH_2  2019-12-18 23:49:51
2  76561198220441373  403640_ACH_3  2019-12-19 23:05:07
3  76561198220441373  403640_ACH_4  2019-12-24 05:50:49
4  76561198220441373  403640_ACH_5  2023-04-19 22:39:36

In [27]:
print("df_history_steam shape")
print(df_history_steam.shape)

print()

print("df_history_steam info")
print(df_history_steam.info())
print()

print("df_history_steam describe")
df_history_steam.describe(include='all')

print()

print("df_history_steam nombre de valeur manquante par colonne")
print(df_history_steam.isnull().sum())

df_history_steam shape
(10693879, 3)

df_history_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10693879 entries, 0 to 10693878
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   playerid       int64
 1   achievementid  object
 2   date_acquired  object
dtypes: int64(1), object(2)
memory usage: 244.8+ MB
None

df_history_steam describe

df_history_steam nombre de valeur manquante par colonne
playerid         0
achievementid    0
date_acquired    0
dtype: int64

In [28]:
df_players_steam = pd.read_csv("steam/players.csv")
df_players_steam.head()

            playerid     country              created
0  76561198287452552      Brazil  2016-03-02 06:14:20
1  76561198040436563      Israel  2011-04-10 17:10:06
2  76561198049686270         NaN  2011-09-28 21:43:59
3  76561198155814250  Kazakhstan  2014-09-24 19:52:47
4  76561198119605821         NaN  2013-12-26 00:25:50

In [29]:
print("df_players_steam shape")
print(df_players_steam.shape)

print()

print("df_players_steam info")
print(df_players_steam.info())
print()

print("df_players_steam describe")
df_players_steam.describe(include='all')

print()

print("df_players_steam nombre de valeur manquante par colonne")
print(df_players_steam.isnull().sum())

df_players_steam shape
(424683, 3)

df_players_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424683 entries, 0 to 424682
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  424683 non-null  int64
 1   country   246815 non-null  object
 2   created   377014 non-null  object
dtypes: int64(1), object(2)
memory usage: 9.7+ MB
None

df_players_steam describe

df_players_steam nombre de valeur manquante par colonne
playerid         0
country     177868
created      47669
dtype: int64

        La country n'est pas renseignée dans 54% des lignes, la date de création n'est pas renseignée dans 11% des lignes

In [30]:
df_prices_steam = pd.read_csv("steam/prices.csv")
df_prices_steam.head()

    gameid  usd  eur  gbp  jpy  rub date_acquired
0  3281560  NaN  NaN  NaN  NaN  NaN    2024-11-28
1  3280930  NaN  NaN  NaN  NaN  NaN    2024-11-28
2  3280770  NaN  NaN  NaN  NaN  NaN    2024-11-28
3  3279790  NaN  NaN  NaN  NaN  NaN    2024-11-28
4  3278320  NaN  NaN  NaN  NaN  NaN    2024-11-28

In [31]:
print("df_prices_steam shape")
print(df_prices_steam.shape)

print()

print("df_prices_steam info")
print(df_prices_steam.info())
print()

print("df_prices_steam describe")
df_prices_steam.describe(include='all')

print()

print("df_prices_steam nombre de valeur manquante par colonne")
print(df_prices_steam.isnull().sum())

df_prices_steam shape
(4414273, 7)

df_prices_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4414273 entries, 0 to 4414272
Data columns (total 7 columns):
 #   Column         Dtype
---  ------         -----
 0   gameid         int64
 1   usd            float64
 2   eur            float64
 3   gbp            float64
 4   jpy            float64
 5   rub            float64
 6   date_acquired  object
dtypes: float64(5), int64(1), object(1)
memory usage: 235.7+ MB
None

df_prices_steam describe

df_prices_steam nombre de valeur manquante par colonne
gameid                 0
usd               907148
eur              1703086
gbp               908184
jpy               919973
rub              1006291
date_acquired          0
dtype: int64

        Le prix en usd n'est pas renseigné dans 20% des lignes
        Le prix en eur n'est pas renseigné dans 38% des lignes
        Le prix en gbp n'est pas renseigné dans 20% des lignes
        Le prix en jpy n'est pas renseigné dans 21% des lignes
        Le prix en rub n'est pas renseigné dans 23% des lignes

In [32]:
df_private_steamids_steam = pd.read_csv("steam/private_steamids.csv")
df_private_steamids_steam.head()

            playerid
0  76561199169391260
1  76561198960514099
2  76561198172657855
3  76561198140146975
4  76561199570942703

In [33]:
print("df_private_steamids_steam shape")
print(df_private_steamids_steam.shape)

print()

print("df_private_steamids_steam info")
print(df_private_steamids_steam.info())
print()

print("df_private_steamids_steam describe")
df_private_steamids_steam.describe(include='all')

print()

print("df_private_steamids_steam nombre de valeur manquante par colonne")
print(df_private_steamids_steam.isnull().sum())

df_private_steamids_steam shape
(227963, 1)

df_private_steamids_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227963 entries, 0 to 227962
Data columns (total 1 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  227963 non-null  int64
dtypes: int64(1)
memory usage: 1.7 MB
None

df_private_steamids_steam describe

df_private_steamids_steam nombre de valeur manquante par colonne
playerid    0
dtype: int64

        RAS

In [34]:
df_purchased_games_steam = pd.read_csv("steam/purchased_games.csv")
df_purchased_games_steam.head()

            playerid                                            library
0  76561198060698936  [60, 1670, 3830, 1600, 2900, 2910, 2920, 4800,...
1  76561198287452552  [10, 80, 100, 240, 2990, 6880, 6910, 6920, 698...
2  76561198040436563  [10, 80, 100, 300, 20, 30, 40, 50, 60, 70, 130...
3  76561198042412488  [300, 240, 220, 320, 360, 4300, 4800, 4000, 61...
4  76561198119605821  [47870, 108600, 550, 271590, 331470, 381210, 2...

In [35]:
print("df_purchased_games_steam shape")
print(df_purchased_games_steam.shape)

print()

print("df_purchased_games_steam info")
print(df_purchased_games_steam.info())
print()

print("df_purchased_games_steam describe")
df_purchased_games_steam.describe(include='all')

print()

print("df_purchased_games_steam nombre de valeur manquante par colonne")
print(df_purchased_games_steam.isnull().sum())

df_purchased_games_steam shape
(102548, 2)

df_purchased_games_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102548 entries, 0 to 102547
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  102548 non-null  int64
 1   library   46941 non-null   object
dtypes: int64(1), object(1)
memory usage: 1.6+ MB
None

df_purchased_games_steam describe

df_purchased_games_steam nombre de valeur manquante par colonne
playerid        0
library     55607
dtype: int64

        La colonne libray n'est pas renseignée dans 54% des lignes

In [36]:
df_reviews_steam = pd.read_csv("steam/reviews.csv")
df_reviews_steam.head()

,reviewid,playerid,gameid,review,helpful,funny,awards,posted
0,639543,76561198796340888,730,Goud gamę i have 3 vac ban acont but i stilll ...,0,0,0,2018-03-22
1,639544,76561198028706627,393380,---{ Graphics }---☐ You forget what reality is...,0,0,0,2025-01-03
2,639545,76561198028706627,10,One of the best FPS games :),0,0,0,2012-05-13
3,639546,76561198049356580,469600,gayet güzel w3 havasını yakalıyor,0,0,0,2018-04-21
4,639547,76561198272817436,730,ONE OF THE GAMES I COME BACK TO,2,0,0,2020-01-23

In [37]:
print("df_reviews_steam shape")
print(df_reviews_steam.shape)

print()

print("df_reviews_steam info")
print(df_reviews_steam.info())
print()

print("df_reviews_steam describe")
df_reviews_steam.describe(include='all')

print()

print("df_reviews_steam nombre de valeur manquante par colonne")
print(df_reviews_steam.isnull().sum())

df_reviews_steam shape
(1204534, 8)

df_reviews_steam info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1204534 entries, 0 to 1204533
Data columns (total 8 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   reviewid  1204534 non-null  int64
 1   playerid  1204534 non-null  int64
 2   gameid    1204534 non-null  int64
 3   review    1202437 non-null  object
 4   helpful   1204534 non-null  int64
 5   funny     1204534 non-null  int64
 6   awards    1204534 non-null  int64
 7   posted    1204534 non-null  object
dtypes: int64(6), object(2)
memory usage: 73.5+ MB
None

df_reviews_steam describe

df_reviews_steam nombre de valeur manquante par colonne
reviewid       0
playerid       0
gameid         0
review      2097
helpful        0
funny          0
awards         0
posted         0
dtype: int64

In [38]:
print("df_reviews_steam nombre de valeur manquante par colonne")
print(df_reviews_steam.isnull().sum())

df_reviews_steam nombre de valeur manquante par colonne
reviewid       0
playerid       0
gameid         0
review      2097
helpful        0
funny          0
awards         0
posted         0
dtype: int64

        Colonne review non renseignée dans 0.1% des lignes

In [39]:
df_achievements_xbox = pd.read_csv("xbox/achievements.csv")
df_achievements_xbox.head()

,achievementid,gameid,title,description,points
0,751069_6114697,751069,Sweet Dreams,Go to sleep and wake up feeling refreshed,50.0
1,751069_6114698,751069,Lumberjack,Chop your first tree,50.0
2,751069_6114699,751069,Miner,Mine your first stone,50.0
3,751069_6114700,751069,Cook,Cook your first meal,50.0
4,751069_6114701,751069,Forager,Collect your first berries,50.0

In [40]:
print("df_achievements_xbox shape")
print(df_achievements_xbox.shape)

print()

print("df_achievements_xbox info")
print(df_achievements_xbox.info())
print()

print("df_achievements_xbox describe")
df_achievements_xbox.describe(include='all')

print()

print("df_achievements_xbox nombre de valeur manquante par colonne")
print(df_achievements_xbox.isnull().sum())

df_achievements_xbox shape
(351111, 5)

df_achievements_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351111 entries, 0 to 351110
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   achievementid  351111 non-null  object
 1   gameid         351111 non-null  int64
 2   title          351110 non-null  object
 3   description    351057 non-null  object
 4   points         350233 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 13.4+ MB
None

df_achievements_xbox describe

df_achievements_xbox nombre de valeur manquante par colonne
achievementid      0
gameid             0
title              1
description       54
points           878
dtype: int64

In [41]:
df_achievements_xbox['points'].value_counts()

points
10.0     62691
15.0     56069
20.0     48030
30.0     39769
50.0     27951
         ...
188.0        1
171.0        1
82.0         1
104.0        1
365.0        1
Name: count, Length: 158, dtype: int64

        Colonne points on renseignée dans 0.25% des lignes

In [42]:
df_games_xbox = pd.read_csv("xbox/games.csv")
df_games_xbox.head()

,gameid,title,developers,publishers,genres,supported_languages,release_date
0,1253,Tomb Raider: Legend,['crystal dynamics'],['Crystal Dynamics'],"['Action', 'Adventure', 'strategy', 'Simulation']","['French', 'Spanish', 'German', 'Italian']",2009-08-11
1,749026,SANYA,['helpnode'],['Samustai'],"['Adventure', 'Point & Click']",NaN,2024-11-22
2,747223,Sky Roll!,['Entity3'],['Entity3'],['Platformer'],NaN,2024-11-22
3,727440,Rogue Flight,NaN,NaN,NaN,NaN,2024-10-25
4,750229,Infernitos,['AFIL Games'],['AFIL Games'],['Puzzle'],NaN,2024-12-18

In [43]:
print("df_games_xbox shape")
print(df_games_xbox.shape)

print()

print("df_games_xbox info")
print(df_games_xbox.info())
print()

print("df_games_xbox describe")
df_games_xbox.describe(include='all')

print()

print("df_games_xbox nombre de valeur manquante par colonne")
print(df_games_xbox.isnull().sum())

df_games_xbox shape
(10489, 7)

df_games_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10489 entries, 0 to 10488
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gameid               10489 non-null  int64
 1   title                10489 non-null  object
 2   developers           9913 non-null   object
 3   publishers           9944 non-null   object
 4   genres               9884 non-null   object
 5   supported_languages  3842 non-null   object
 6   release_date         10489 non-null  object
dtypes: int64(1), object(6)
memory usage: 573.7+ KB
None

df_games_xbox describe

df_games_xbox nombre de valeur manquante par colonne
gameid                    0
title                     0
developers              576
publishers              545
genres                  605
supported_languages    6647
release_date              0
dtype: int64

        Supported langage absent de 63% des lignes

In [44]:
df_history_xbox = pd.read_csv("xbox/history.csv")
df_history_xbox.head()

   playerid   achievementid        date_acquired
0   2466527  750641_6112019  2024-11-27 22:37:31
1   2466527  750641_6111985  2024-11-27 00:14:26
2   2466527  557191_4661215  2024-11-27 16:15:38
3   2466527  557191_4661196  2024-11-27 12:15:35
4   2466527  557191_4661203  2024-11-27 11:25:50

In [45]:
print("df_history_xbox shape")
print(df_history_xbox.shape)

print()

print("df_history_xbox info")
print(df_history_xbox.info())
print()

print("df_history_xbox describe")
df_history_xbox.describe(include='all')

print()

print("df_history_xbox nombre de valeur manquante par colonne")
print(df_history_xbox.isnull().sum())

df_history_xbox shape
(15275900, 3)

df_history_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15275900 entries, 0 to 15275899
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   playerid       int64
 1   achievementid  object
 2   date_acquired  object
dtypes: int64(1), object(2)
memory usage: 349.6+ MB
None

df_history_xbox describe

df_history_xbox nombre de valeur manquante par colonne
playerid         0
achievementid    0
date_acquired    0
dtype: int64

        RAS

In [46]:
df_players_xbox = pd.read_csv("xbox/players.csv")
df_players_xbox.head()

   playerid         nickname
0    848738           smrnov
1    848736  RedmptionDenied
2   1470783          Healtti
3    848735        jimmyhova
4    848739       Stallion83

In [47]:
print("df_players_xbox shape")
print(df_players_xbox.shape)

print()

print("df_players_xbox info")
print(df_players_xbox.info())
print()

print("df_players_xbox describe")
df_players_xbox.describe(include='all')

print()

print("df_players_xbox nombre de valeur manquante par colonne")
print(df_players_xbox.isnull().sum())

df_players_xbox shape
(274450, 2)

df_players_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274450 entries, 0 to 274449
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  274450 non-null  int64
 1   nickname  274449 non-null  object
dtypes: int64(1), object(1)
memory usage: 4.2+ MB
None

df_players_xbox describe

df_players_xbox nombre de valeur manquante par colonne
playerid    0
nickname    1
dtype: int64

        RAS

In [48]:
df_prices_xbox = pd.read_csv("xbox/prices.csv")
df_prices_xbox.head()

   gameid    usd    eur    gbp  jpy     rub date_acquired
0    1253  19.99  19.99  15.99  NaN  1772.0    2025-02-22
1  727440  17.99  17.99  14.99  NaN  1595.0    2025-02-22
2  747995   4.79   4.79   3.99  NaN   425.0    2025-02-22
3  727135  17.99  17.99  14.99  NaN  1595.0    2025-02-22
4  748541  19.99  19.99  16.74  NaN  1772.0    2025-02-22

In [49]:
print("df_prices_xbox shape")
print(df_prices_xbox.shape)

print()

print("df_prices_xbox info")
print(df_prices_xbox.info())
print()

print("df_prices_xbox describe")
df_prices_xbox.describe(include='all')

print()

print("df_prices_xbox nombre de valeur manquante par colonne")
print(df_prices_xbox.isnull().sum())

df_prices_xbox shape
(22638, 7)

df_prices_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22638 entries, 0 to 22637
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gameid         22638 non-null  int64
 1   usd            16003 non-null  float64
 2   eur            15269 non-null  float64
 3   gbp            15812 non-null  float64
 4   jpy            0 non-null      float64
 5   rub            14377 non-null  float64
 6   date_acquired  22638 non-null  object
dtypes: float64(5), int64(1), object(1)
memory usage: 1.2+ MB
None

df_prices_xbox describe

df_prices_xbox nombre de valeur manquante par colonne
gameid               0
usd               6635
eur               7369
gbp               6826
jpy              22638
rub               8261
date_acquired        0
dtype: int64

In [50]:
print("df_prices_xbox nombre de valeur manquante par colonne")
print(df_prices_xbox.isnull().sum())

df_prices_xbox nombre de valeur manquante par colonne
gameid               0
usd               6635
eur               7369
gbp               6826
jpy              22638
rub               8261
date_acquired        0
dtype: int64

        Le prix en usd n'est pas renseigné dans 29% des lignes
        Le prix en eur n'est pas renseigné dans 32% des lignes
        Le prix en gbp n'est pas renseigné dans 30% des lignes
        Le prix en jpy n'est pas renseigné dans 100% des lignes
        Le prix en rub n'est pas renseigné dans 36% des lignes

In [51]:
df_purchased_games_xbox = pd.read_csv("steam/purchased_games.csv")
df_purchased_games_xbox.head()

            playerid                                            library
0  76561198060698936  [60, 1670, 3830, 1600, 2900, 2910, 2920, 4800,...
1  76561198287452552  [10, 80, 100, 240, 2990, 6880, 6910, 6920, 698...
2  76561198040436563  [10, 80, 100, 300, 20, 30, 40, 50, 60, 70, 130...
3  76561198042412488  [300, 240, 220, 320, 360, 4300, 4800, 4000, 61...
4  76561198119605821  [47870, 108600, 550, 271590, 331470, 381210, 2...

In [52]:
print("df_purchased_games_xbox shape")
print(df_purchased_games_xbox.shape)

print()

print("df_purchased_games_xbox info")
print(df_purchased_games_xbox.info())
print()

print("df_purchased_games_xbox describe")
df_purchased_games_xbox.describe(include='all')

print()

print("df_purchased_games_xbox nombre de valeur manquante par colonne")
print(df_purchased_games_xbox.isnull().sum())

df_purchased_games_xbox shape
(102548, 2)

df_purchased_games_xbox info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102548 entries, 0 to 102547
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  102548 non-null  int64
 1   library   46941 non-null   object
dtypes: int64(1), object(1)
memory usage: 1.6+ MB
None

df_purchased_games_xbox describe

df_purchased_games_xbox nombre de valeur manquante par colonne
playerid        0
library     55607
dtype: int64

        library non renseigné dans 54% des lignes

In [53]:
df_games_playstation["gameid"].describe()

count     23151.000000
mean     433061.860136
std      248153.412814
min           1.000000
25%      191745.000000
50%      508540.000000
75%      628879.000000
max      766555.000000
Name: gameid, dtype: float64

        playstation gameid min = 1 max = 766555

In [54]:
df_games_steam["gameid"].min()

np.int64(10)

        steam gameid 10 = 1 max = 3441890

In [55]:
df_games_xbox["gameid"].describe()

count     10489.000000
mean     317482.376871
std      268358.416190
min        1040.000000
25%       10815.000000
50%      392711.000000
75%      565151.000000
max      766495.000000
Name: gameid, dtype: float64

        xbox gameid min = 1040 max = 766495

In [56]:
print("player id playsation min", df_players_playstation["playerid"].min())
print("player id playsation max", df_players_playstation["playerid"].max())

player id playsation min 2
player id playsation max 4749685

In [57]:
print("player id steam min", df_players_steam["playerid"].min())
print("player id steam max", df_players_steam["playerid"].max())

player id steam min 76561197960265861
player id steam max 76561199815552638

In [58]:
print("player id xbox min", df_players_xbox["playerid"].min())
print("player id xbox max", df_players_xbox["playerid"].max())

player id xbox min 458746
player id xbox max 4746786

In [59]:
df_history_playstation['date_acquired'] = pd.to_datetime(arg = df_history_playstation['date_acquired'],errors='coerce')

df_history_playstation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19510083 entries, 0 to 19510082
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   playerid       int64
 1   achievementid  object
 2   date_acquired  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 446.6+ MB

## 2) Nettoyage des données

### Ajout de la colonne platfome à aux dataset achievements

In [60]:
df_achievements_playstation['platform'] = 'playstation'
df_achievements_playstation.head()

,achievementid,gameid,title,description,rarity,platform
0,749980_6103480,749980,Platinum Cup,Get all the trophies,Platinum,playstation
1,749980_6103481,749980,Arcade Beginner,Finish race,Bronze,playstation
2,749980_6103482,749980,Arcade Beginner Dirt,Finish race,Bronze,playstation
3,749980_6103483,749980,Arcade Intermediate,Finish race,Silver,playstation
4,749980_6103484,749980,Arcade Advanced,Finish race,Silver,playstation

In [61]:
df_achievements_steam['platform'] = 'steam'
df_achievements_steam.head()

,achievementid,gameid,title,description,platform
0,2621440_ACH_FIRST_KILL,2621440,FIRST KILL,You should kill ONE enemy.,steam
1,2621440_ACH_0_LEVEL_COMPLETED,2621440,TUTORIAL COMPLETED,You should complete tutorial.,steam
2,2621440_ACH_1_LEVEL_COMPLETED,2621440,FIRST LEVEL,You should complete first level,steam
3,2621440_ACH_2_LEVEL_COMPLETED,2621440,SECOND LEVEL,You should complete second level,steam
4,2621440_ACH_3_LEVEL_COMPLETED,2621440,THIRD LEVEL,You should complete third level,steam

In [62]:
df_achievements_xbox['platform'] = 'xbox'
df_achievements_xbox.head()

,achievementid,gameid,title,description,points,platform
0,751069_6114697,751069,Sweet Dreams,Go to sleep and wake up feeling refreshed,50.0,xbox
1,751069_6114698,751069,Lumberjack,Chop your first tree,50.0,xbox
2,751069_6114699,751069,Miner,Mine your first stone,50.0,xbox
3,751069_6114700,751069,Cook,Cook your first meal,50.0,xbox
4,751069_6114701,751069,Forager,Collect your first berries,50.0,xbox

### Ajout de la valeur unknown dans les colonnes ayant des lignes vide des dataset achievement

In [63]:
df_achievements_playstation = df_achievements_playstation.fillna({'title': 'unknown', 'description': 'unknown'})

print("df_achievements_playstation nombre de valeur manquante par colonne")
df_achievements_playstation.isnull().sum()

df_achievements_playstation nombre de valeur manquante par colonne

achievementid    0
gameid           0
title            0
description      0
rarity           0
platform         0
dtype: int64

In [64]:
df_achievements_steam = df_achievements_steam.fillna({'title': 'unknown', 'description': 'unknown'})

print("df_achievements_steam nombre de valeur manquante par colonne")
df_achievements_steam.isnull().sum()

df_achievements_steam nombre de valeur manquante par colonne

achievementid    0
gameid           0
title            0
description      0
platform         0
dtype: int64

In [65]:
df_achievements_xbox = df_achievements_xbox.fillna({'title': 'unknown', 'description': 'unknown', 'points' : -1})

print("df_achievements_xbox nombre de valeur manquante par colonne")
df_achievements_xbox.isnull().sum()

df_achievements_xbox nombre de valeur manquante par colonne

achievementid    0
gameid           0
title            0
description      0
points           0
platform         0
dtype: int64

### Fusion des datasets achievement

In [66]:
df_achievements = pd.concat([df_achievements_playstation,df_achievements_steam, df_achievements_xbox], axis = 0, ignore_index=True)
df_achievements

,achievementid,gameid,title,description,rarity,platform,points
0,749980_6103480,749980,Platinum Cup,Get all the trophies,Platinum,playstation,NaN
1,749980_6103481,749980,Arcade Beginner,Finish race,Bronze,playstation,NaN
2,749980_6103482,749980,Arcade Beginner Dirt,Finish race,Bronze,playstation,NaN
3,749980_6103483,749980,Arcade Intermediate,Finish race,Silver,playstation,NaN
4,749980_6103484,749980,Arcade Advanced,Finish race,Silver,playstation,NaN
...,...,...,...,...,...,...,...
3136696,333262_6158528,333262,Animal Farm,Reach 50 Vivarium capacity.,NaN,xbox,1.0
3136697,333262_6158529,333262,Wormageddon,Destroy a Voidworm nest.,NaN,xbox,1.0
3136698,333262_6158530,333262,That's No Asteroid,Capture a Cutholoid with a Gravity Snare.,NaN,xbox,1.0
3136699,333262_6158531,333262,X Marks the Spot,Discover Captain Ness's Treasure Hoard.,NaN,xbox,1.0
3136700,333262_6158532,333262,Beastmaster,Defeat the endgame crisis without building a s...,NaN,xbox,1.0

In [67]:
#Valeur vide pour la plateforme
df_achievements = df_achievements.fillna({'rarity': 'unknown for platform', 'points' : -1})

### L'identifiant du jeu est préfixé par la plateforme

In [68]:
df_achievements['gameid'] = df_achievements.apply(
    lambda x: str(x['gameid'])+'_'+x['platform'],
    axis= 1
)

df_achievements

,achievementid,gameid,title,description,rarity,platform,points
0,749980_6103480,749980_playstation,Platinum Cup,Get all the trophies,Platinum,playstation,-1.0
1,749980_6103481,749980_playstation,Arcade Beginner,Finish race,Bronze,playstation,-1.0
2,749980_6103482,749980_playstation,Arcade Beginner Dirt,Finish race,Bronze,playstation,-1.0
3,749980_6103483,749980_playstation,Arcade Intermediate,Finish race,Silver,playstation,-1.0
4,749980_6103484,749980_playstation,Arcade Advanced,Finish race,Silver,playstation,-1.0
...,...,...,...,...,...,...,...
3136696,333262_6158528,333262_xbox,Animal Farm,Reach 50 Vivarium capacity.,unknown for platform,xbox,1.0
3136697,333262_6158529,333262_xbox,Wormageddon,Destroy a Voidworm nest.,unknown for platform,xbox,1.0
3136698,333262_6158530,333262_xbox,That's No Asteroid,Capture a Cutholoid with a Gravity Snare.,unknown for platform,xbox,1.0
3136699,333262_6158531,333262_xbox,X Marks the Spot,Discover Captain Ness's Treasure Hoard.,unknown for platform,xbox,1.0
3136700,333262_6158532,333262_xbox,Beastmaster,Defeat the endgame crisis without building a s...,unknown for platform,xbox,1.0

### Ajout de la colonne platforme aux dataset games

In [69]:
df_games_playstation['main_platform'] = 'playstation'
df_games_playstation.head()

,gameid,title,platform,developers,publishers,genres,supported_languages,release_date,main_platform
0,749375,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22,playstation
1,749839,Sunforge Solar Survival,PS4,['GrizzlyGames'],['GrizzlyGames'],NaN,NaN,2024-11-21,playstation
2,749347,Find Love Or Die Trying,PS5,['Sunseeker Games'],['Ratalaika Games'],['Visual Novel'],NaN,2024-11-22,playstation
3,749341,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22,playstation
4,749097,Bust A Block 2,PS5,['ThiGames'],['ThiGames'],['Puzzle'],NaN,2024-11-21,playstation

In [70]:
df_games_steam['main_platform'] = 'steam'
df_games_steam.head()

,gameid,title,developers,publishers,genres,supported_languages,release_date,main_platform
0,3281560,Horror Game To Play With Friends! Playtest,NaN,NaN,NaN,NaN,2024-10-21,steam
1,3280930,Eternals' Path Playtest,NaN,NaN,NaN,NaN,2024-10-17,steam
2,3280770,ANGST: A TALE OF SURVIVAL - Singleplayer Playtest,NaN,NaN,NaN,NaN,2024-10-13,steam
3,3279790,Montabi Playtest,NaN,NaN,NaN,NaN,2024-10-13,steam
4,3278320,파이팅걸 유리 Playtest,NaN,NaN,NaN,NaN,2024-10-12,steam

In [71]:
df_games_xbox['main_platform'] = 'xbox'
df_games_xbox.head()

,gameid,title,developers,publishers,genres,supported_languages,release_date,main_platform
0,1253,Tomb Raider: Legend,['crystal dynamics'],['Crystal Dynamics'],"['Action', 'Adventure', 'strategy', 'Simulation']","['French', 'Spanish', 'German', 'Italian']",2009-08-11,xbox
1,749026,SANYA,['helpnode'],['Samustai'],"['Adventure', 'Point & Click']",NaN,2024-11-22,xbox
2,747223,Sky Roll!,['Entity3'],['Entity3'],['Platformer'],NaN,2024-11-22,xbox
3,727440,Rogue Flight,NaN,NaN,NaN,NaN,2024-10-25,xbox
4,750229,Infernitos,['AFIL Games'],['AFIL Games'],['Puzzle'],NaN,2024-12-18,xbox

### Fusion des dataset games

In [72]:
df_games = pd.concat(objs = [df_games_playstation, df_games_steam, df_games_xbox], axis = 0, ignore_index=True)
df_games

,gameid,title,platform,developers,publishers,genres,supported_languages,release_date,main_platform
0,749375,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22,playstation
1,749839,Sunforge Solar Survival,PS4,['GrizzlyGames'],['GrizzlyGames'],NaN,NaN,2024-11-21,playstation
2,749347,Find Love Or Die Trying,PS5,['Sunseeker Games'],['Ratalaika Games'],['Visual Novel'],NaN,2024-11-22,playstation
3,749341,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],NaN,2024-11-22,playstation
4,749097,Bust A Block 2,PS5,['ThiGames'],['ThiGames'],['Puzzle'],NaN,2024-11-21,playstation
...,...,...,...,...,...,...,...,...,...
131883,163747,Fishing Sim World,NaN,['Dovetail Games'],NaN,['sports'],"['French', 'Spanish', 'German', 'Russian', 'Ch...",2018-09-18,xbox
131884,163627,Construction Simulator 2 US - Console Edition,NaN,NaN,NaN,NaN,"['Japanese', 'French', 'Spanish', 'German', 'I...",2018-09-12,xbox
131885,6817,Saraiva Player,NaN,['Saraiva Player'],['Saraiva Player'],['Video'],NaN,2014-01-21,xbox
131886,6807,SKY ONLINE,NaN,['SKY Brasil'],['SKY Brasil'],['Video'],NaN,2013-11-22,xbox
131887,2519,Crazy Machines Elem.,NaN,['FAKT Software Gmbh'],NaN,"['strategy', 'Simulation', 'puzzle']","['French', 'Spanish', 'German', 'Italian']",2011-08-24,xbox

### Suppression de la colonne supported_languages du dataset games

In [73]:
df_games.drop('supported_languages', axis=1, inplace=True)
df_games

,gameid,title,platform,developers,publishers,genres,release_date,main_platform
0,749375,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],2024-11-22,playstation
1,749839,Sunforge Solar Survival,PS4,['GrizzlyGames'],['GrizzlyGames'],NaN,2024-11-21,playstation
2,749347,Find Love Or Die Trying,PS5,['Sunseeker Games'],['Ratalaika Games'],['Visual Novel'],2024-11-22,playstation
3,749341,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],2024-11-22,playstation
4,749097,Bust A Block 2,PS5,['ThiGames'],['ThiGames'],['Puzzle'],2024-11-21,playstation
...,...,...,...,...,...,...,...,...
131883,163747,Fishing Sim World,NaN,['Dovetail Games'],NaN,['sports'],2018-09-18,xbox
131884,163627,Construction Simulator 2 US - Console Edition,NaN,NaN,NaN,NaN,2018-09-12,xbox
131885,6817,Saraiva Player,NaN,['Saraiva Player'],['Saraiva Player'],['Video'],2014-01-21,xbox
131886,6807,SKY ONLINE,NaN,['SKY Brasil'],['SKY Brasil'],['Video'],2013-11-22,xbox
131887,2519,Crazy Machines Elem.,NaN,['FAKT Software Gmbh'],NaN,"['strategy', 'Simulation', 'puzzle']",2011-08-24,xbox

### Remplacement des valeurs vides par unknown dans les colonnes vide du dataset games

In [74]:
print(df_games.isnull().sum())

gameid                0
title                 3
platform         108737
developers         6152
publishers         6497
genres             6296
release_date          0
main_platform         0
dtype: int64

In [75]:
df_games = df_games.fillna({'title': 'unknown', 'platform': 'unknown', 'developers' : 'unknown', 'publishers': 'unknown', 'genres': 'unknown'})
print(df_games.isnull().sum())

gameid           0
title            0
platform         0
developers       0
publishers       0
genres           0
release_date     0
main_platform    0
dtype: int64

### Ajout d'une colonne main_genre contenant le genre principal d'un jeu

In [76]:
df_games['main_genres'] = df_games['genres'].apply(lambda x: x.strip('[]').replace("'", "").split(',')[0])
df_games

,gameid,title,platform,developers,publishers,genres,release_date,main_platform,main_genres
0,749375,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],2024-11-22,playstation,Puzzle
1,749839,Sunforge Solar Survival,PS4,['GrizzlyGames'],['GrizzlyGames'],unknown,2024-11-21,playstation,unknown
2,749347,Find Love Or Die Trying,PS5,['Sunseeker Games'],['Ratalaika Games'],['Visual Novel'],2024-11-22,playstation,Visual Novel
3,749341,Medieval Match Master,PS4,['Erik Games'],['Erik Games'],['Puzzle'],2024-11-22,playstation,Puzzle
4,749097,Bust A Block 2,PS5,['ThiGames'],['ThiGames'],['Puzzle'],2024-11-21,playstation,Puzzle
...,...,...,...,...,...,...,...,...,...
131883,163747,Fishing Sim World,unknown,['Dovetail Games'],unknown,['sports'],2018-09-18,xbox,sports
131884,163627,Construction Simulator 2 US - Console Edition,unknown,unknown,unknown,unknown,2018-09-12,xbox,unknown
131885,6817,Saraiva Player,unknown,['Saraiva Player'],['Saraiva Player'],['Video'],2014-01-21,xbox,Video
131886,6807,SKY ONLINE,unknown,['SKY Brasil'],['SKY Brasil'],['Video'],2013-11-22,xbox,Video
131887,2519,Crazy Machines Elem.,unknown,['FAKT Software Gmbh'],unknown,"['strategy', 'Simulation', 'puzzle']",2011-08-24,xbox,strategy

In [77]:
df_games.dtypes

gameid            int64
title            object
platform         object
developers       object
publishers       object
genres           object
release_date     object
main_platform    object
main_genres      object
dtype: object

### Conversion des colonnes publishers et developers en list

In [78]:
df_games['developers'] = df_games['developers'].apply(lambda x: x.strip('[]').replace("'", "").split(','))
df_games['publishers'] = df_games['publishers'].apply(lambda x: x.strip('[]').replace("'", "").split(','))
df_games

,gameid,title,platform,developers,publishers,genres,release_date,main_platform,main_genres
0,749375,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
1,749839,Sunforge Solar Survival,PS4,[GrizzlyGames],[GrizzlyGames],unknown,2024-11-21,playstation,unknown
2,749347,Find Love Or Die Trying,PS5,[Sunseeker Games],[Ratalaika Games],['Visual Novel'],2024-11-22,playstation,Visual Novel
3,749341,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
4,749097,Bust A Block 2,PS5,[ThiGames],[ThiGames],['Puzzle'],2024-11-21,playstation,Puzzle
...,...,...,...,...,...,...,...,...,...
131883,163747,Fishing Sim World,unknown,[Dovetail Games],[unknown],['sports'],2018-09-18,xbox,sports
131884,163627,Construction Simulator 2 US - Console Edition,unknown,[unknown],[unknown],unknown,2018-09-12,xbox,unknown
131885,6817,Saraiva Player,unknown,[Saraiva Player],[Saraiva Player],['Video'],2014-01-21,xbox,Video
131886,6807,SKY ONLINE,unknown,[SKY Brasil],[SKY Brasil],['Video'],2013-11-22,xbox,Video
131887,2519,Crazy Machines Elem.,unknown,[FAKT Software Gmbh],[unknown],"['strategy', 'Simulation', 'puzzle']",2011-08-24,xbox,strategy

### Conversion au format date de la colonne relase_date des dataset games

In [79]:
df_games['release_date'] = pd.to_datetime(arg=df_games['release_date'])
df_games

,gameid,title,platform,developers,publishers,genres,release_date,main_platform,main_genres
0,749375,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
1,749839,Sunforge Solar Survival,PS4,[GrizzlyGames],[GrizzlyGames],unknown,2024-11-21,playstation,unknown
2,749347,Find Love Or Die Trying,PS5,[Sunseeker Games],[Ratalaika Games],['Visual Novel'],2024-11-22,playstation,Visual Novel
3,749341,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
4,749097,Bust A Block 2,PS5,[ThiGames],[ThiGames],['Puzzle'],2024-11-21,playstation,Puzzle
...,...,...,...,...,...,...,...,...,...
131883,163747,Fishing Sim World,unknown,[Dovetail Games],[unknown],['sports'],2018-09-18,xbox,sports
131884,163627,Construction Simulator 2 US - Console Edition,unknown,[unknown],[unknown],unknown,2018-09-12,xbox,unknown
131885,6817,Saraiva Player,unknown,[Saraiva Player],[Saraiva Player],['Video'],2014-01-21,xbox,Video
131886,6807,SKY ONLINE,unknown,[SKY Brasil],[SKY Brasil],['Video'],2013-11-22,xbox,Video
131887,2519,Crazy Machines Elem.,unknown,[FAKT Software Gmbh],[unknown],"['strategy', 'Simulation', 'puzzle']",2011-08-24,xbox,strategy

### L'identifiant du jeu est suffixée par la plateforme

In [80]:
df_games['gameid'] = df_games.apply(
    lambda x: str(x['gameid'])+'_'+x['main_platform'],
    axis= 1
)

df_games

,gameid,title,platform,developers,publishers,genres,release_date,main_platform,main_genres
0,749375_playstation,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
1,749839_playstation,Sunforge Solar Survival,PS4,[GrizzlyGames],[GrizzlyGames],unknown,2024-11-21,playstation,unknown
2,749347_playstation,Find Love Or Die Trying,PS5,[Sunseeker Games],[Ratalaika Games],['Visual Novel'],2024-11-22,playstation,Visual Novel
3,749341_playstation,Medieval Match Master,PS4,[Erik Games],[Erik Games],['Puzzle'],2024-11-22,playstation,Puzzle
4,749097_playstation,Bust A Block 2,PS5,[ThiGames],[ThiGames],['Puzzle'],2024-11-21,playstation,Puzzle
...,...,...,...,...,...,...,...,...,...
131883,163747_xbox,Fishing Sim World,unknown,[Dovetail Games],[unknown],['sports'],2018-09-18,xbox,sports
131884,163627_xbox,Construction Simulator 2 US - Console Edition,unknown,[unknown],[unknown],unknown,2018-09-12,xbox,unknown
131885,6817_xbox,Saraiva Player,unknown,[Saraiva Player],[Saraiva Player],['Video'],2014-01-21,xbox,Video
131886,6807_xbox,SKY ONLINE,unknown,[SKY Brasil],[SKY Brasil],['Video'],2013-11-22,xbox,Video
131887,2519_xbox,Crazy Machines Elem.,unknown,[FAKT Software Gmbh],[unknown],"['strategy', 'Simulation', 'puzzle']",2011-08-24,xbox,strategy

### Ajout de la colonne platforme aux dataset history

In [81]:
df_history_playstation['platform'] = 'playstation'
df_history_playstation.head()

   playerid   achievementid       date_acquired     platform
0   1911732  670209_5436079 2024-11-28 10:23:24  playstation
1   1911732  670209_5436078 2024-11-28 09:36:41  playstation
2   1911732  670209_5436077 2024-11-28 08:31:54  playstation
3   1911732  670209_5436076 2024-11-28 08:19:23  playstation
4   1911732  658551_5368954 2024-10-05 13:12:35  playstation

In [82]:
df_history_steam['platform'] = 'steam'
df_history_steam.head()

            playerid achievementid        date_acquired platform
0  76561198220441373  403640_ACH_1  2019-12-18 15:33:43    steam
1  76561198220441373  403640_ACH_2  2019-12-18 23:49:51    steam
2  76561198220441373  403640_ACH_3  2019-12-19 23:05:07    steam
3  76561198220441373  403640_ACH_4  2019-12-24 05:50:49    steam
4  76561198220441373  403640_ACH_5  2023-04-19 22:39:36    steam

In [83]:
df_history_xbox['platform'] = 'xbox'
df_history_xbox.head()

   playerid   achievementid        date_acquired platform
0   2466527  750641_6112019  2024-11-27 22:37:31     xbox
1   2466527  750641_6111985  2024-11-27 00:14:26     xbox
2   2466527  557191_4661215  2024-11-27 16:15:38     xbox
3   2466527  557191_4661196  2024-11-27 12:15:35     xbox
4   2466527  557191_4661203  2024-11-27 11:25:50     xbox

### Fusion des dataset history

In [84]:
df_history = pd.concat([df_history_playstation, df_history_steam, df_history_xbox], axis = 0, ignore_index=True)
df_history

          playerid   achievementid        date_acquired     platform
0          1911732  670209_5436079  2024-11-28 10:23:24  playstation
1          1911732  670209_5436078  2024-11-28 09:36:41  playstation
2          1911732  670209_5436077  2024-11-28 08:31:54  playstation
3          1911732  670209_5436076  2024-11-28 08:19:23  playstation
4          1911732  658551_5368954  2024-10-05 13:12:35  playstation
...            ...             ...                  ...          ...
45479857    513481     2223_297052  2009-12-03 00:10:57         xbox
45479858    513481     2223_304919  2009-12-01 19:22:26         xbox
45479859    513481     2223_304920  2009-12-01 18:33:36         xbox
45479860    513481     2223_304921  2009-12-01 18:22:18         xbox
45479861    513481     2223_304922  2009-12-01 18:12:40         xbox

[45479862 rows x 4 columns]

### Séparation de la colonne date_acquired du dataset history en date et heure

In [ ]:
df_history['date_acquired'] = pd.to_datetime(arg = df_history['date_acquired'],errors='coerce')

df_history['date_acquired_date'] = df_history['date_acquired'].dt.strftime('%Y-%m-%d')

df_history['date_acquired_time'] = df_history['date_acquired'].dt.strftime('%H:%M:%S')

df_history.dtypes

In [ ]:
df_history

### L'identifiant du jeu est suffixé par la plateforme

In [ ]:
df_history['playerid'] = df_history.apply(
    lambda x: str(x['playerid'])+'_'+x['platform'],
    axis= 1
)

df_history

### Ajout de la colonne platform à aux dataset players

In [ ]:
df_players_playstation['platform'] = 'playstation'
df_players_playstation.head()

In [ ]:
df_players_steam['platform'] = 'steam'
df_players_steam.head()

In [ ]:
df_players_xbox['platform'] = 'xbox'
df_players_xbox.head()

### Fusion des dataset players

In [ ]:
df_players = pd.concat([df_players_playstation, df_players_steam, df_players_xbox], axis = 0, ignore_index= True)
df_players

### Suppression de la colonne nickname

In [ ]:
df_players.drop('nickname', axis=1, inplace=True)
df_players

### Séparation de la colonne created du dataset players en date et en heure

In [ ]:
df_players['created'] = pd.to_datetime(arg = df_players['created'],errors='coerce')

df_players['created_date'] = df_players['created'].dt.strftime('%Y-%m-%d')

df_players['created_time'] = df_players['created'].dt.strftime('%H:%M:%S')

df_players.dtypes

### Remplacement des valeurs vides par unknown dans les colonnes vide du dataset players

In [ ]:
print(df_players.isnull().sum())

In [ ]:
df_players = df_players.fillna({'country': 'unknown', 'created': 'unknown', 'created_date' : 'unknown', 'created_time' : 'unknown'})

print(df_players.isnull().sum())
df_players

### Ajout d'un identifiant au dataset player qui est une concatenation de la colonne playerid et de la colonne platform

In [ ]:
df_players['playerid'] = df_players.apply(
    lambda x: str(x['playerid'])+'_'+x['platform'],
    axis= 1
)

df_players

### Ajout de la colonne platforme aux datasets price

In [ ]:
df_prices_playstation['platform'] = 'playstation'
df_prices_playstation.head()

In [ ]:
df_prices_steam['platform'] = 'steam'
df_prices_steam.head()

In [ ]:
df_prices_xbox['platform'] = 'xbox'
df_prices_xbox.head()

### Fusion des dataset price

In [ ]:
df_prices = pd.concat([df_prices_playstation, df_prices_steam, df_prices_xbox], axis = 0, ignore_index= True)
df_prices

### Remplacement des valeurs vides par -1 dans les colonnes vide du dataset prices

In [ ]:
print(df_prices.isnull().sum())

In [ ]:
df_prices = df_prices.fillna({'usd': -1, 'eur': -1, 'gbp' : -1, 'jpy': -1, 'rub': -1})
print(df_prices.isnull().sum())

### Conversion de la colonne date_acquired en date

In [ ]:
df_prices['date_acquired'] = pd.to_datetime(arg = df_prices['date_acquired'],errors='coerce')
df_prices.dtypes

### L'identifiant du jeu est suffixé par la plateforme

In [ ]:
df_prices['gameid'] = df_prices.apply(
    lambda x: str(x['gameid'])+'_'+x['platform'],
    axis= 1
)

df_prices

### Ajout de la colonne platforme aux dataset purchased_games

In [ ]:
df_purchased_games_playstation['platform'] = 'playstation'
df_purchased_games_playstation.head()

In [ ]:
df_purchased_games_steam['platform'] = 'steam'
df_purchased_games_steam.head()

In [ ]:
df_purchased_games_xbox['platform'] = 'xbox'
df_purchased_games_xbox.head()

### Fusion des dataset purchased_games

In [ ]:
df_purchased_games = pd.concat([df_purchased_games_playstation, df_purchased_games_steam, df_purchased_games_xbox], axis = 0, ignore_index= True)
df_purchased_games.head()

### Dataset contenant le nombre de jeux acheté par joueur

In [ ]:

df_purchased_games_by_player = df_purchased_games.copy(deep=False)

df_purchased_games_by_player['nb_purchased_games'] = df_purchased_games['library'].apply(
    lambda x: 0 if isinstance(x, numbers.Number) and math.isnan(x) else len(x.strip('[]').replace("'", "").split(','))
)
df_purchased_games_by_player.drop('library', axis=1, inplace=True)
df_purchased_games_by_player

In [ ]:
df_purchased_games

### L'identifiant du joueur est suffixé par la plateforme

In [ ]:
df_purchased_games['playerid'] = df_purchased_games.apply(
    lambda x: str(x['playerid'])+'_'+x['platform'],
    axis= 1
)

df_purchased_games

### Remplacement des valeurs vides par unknown dans les colonnes vide du dataset review

In [ ]:
df_reviews_steam = df_reviews_steam.fillna({'review': 'unknown'})
print(df_reviews_steam.isnull().sum())

### L'identifiant du jeu est suffixé par la plateforme

In [ ]:
df_reviews_steam['gameid'] = df_reviews_steam.apply(
    lambda x: str(x['gameid'])+'_steam',
    axis= 1
)

df_reviews_steam

### L'identifiant du joueur est suffixé par la plateforme

In [ ]:
df_reviews_steam['playerid'] = df_reviews_steam.apply(
    lambda x: str(x['playerid'])+'_steam',
    axis= 1
)

df_reviews_steam

### Nombre de revue par jeu

In [ ]:
df_reviews_steam_by_gameid = df_reviews_steam.groupby('gameid').size().reset_index(name='nb_revue')
df_reviews_steam_by_gameid['sum_helpful'] = df_reviews_steam.groupby('gameid')['helpful'].sum().reset_index(name='sum_helpful')['sum_helpful']
df_reviews_steam_by_gameid['sum_funny'] = df_reviews_steam.groupby('gameid')['funny'].sum().reset_index(name='sum_funny')['sum_funny']
df_reviews_steam_by_gameid['sum_awards'] = df_reviews_steam.groupby('gameid')['awards'].sum().reset_index(name='sum_awards')['sum_awards']

df_reviews_steam_by_gameid

### Nombre de revue par joueur

In [ ]:
df_reviews_steam_by_playerid = df_reviews_steam.groupby('playerid').size().reset_index(name='nb_revue')
df_reviews_steam_by_playerid['sum_helpful'] = df_reviews_steam.groupby('playerid')['helpful'].sum().reset_index(name='sum_helpful')['sum_helpful']
df_reviews_steam_by_playerid['sum_funny'] = df_reviews_steam.groupby('playerid')['funny'].sum().reset_index(name='sum_funny')['sum_funny']
df_reviews_steam_by_playerid['sum_awards'] = df_reviews_steam.groupby('playerid')['awards'].sum().reset_index(name='sum_awards')['sum_awards']

df_reviews_steam_by_playerid

## 3) Analyse des datasets

### Prix en dollar par plateforme et genre

In [ ]:
df_prices.head()

In [ ]:
df_games.head()

In [ ]:
df_games_prices = pd.merge(right=df_prices, left=df_games, on='gameid', how='left')

prices_by_plateforme_and_genre = df_games_prices.groupby(['main_platform', 'main_genres'])['usd'].mean().reset_index().sort_values(ascending=False, by='usd')
prices_by_plateforme_and_genre

### Genres de jeux les plus repandu

In [ ]:
genre_by_plateforme = df_games.groupby(['main_platform', 'main_genres']).size().reset_index(name='nb_genre').sort_values(by='nb_genre', ascending=False)
genre_by_plateforme

### Nombre de jeu par plateforme

In [ ]:
game_by_plateforme = df_games.groupby(['main_platform']).size().reset_index(name='nb_game').sort_values(by='nb_game', ascending=False)
game_by_plateforme

### Nombre de joueur par pays

In [ ]:
players_with_country = df_players[df_players['country'] != 'unknown']
player_by_country = players_with_country.groupby(['country', 'platform']).size().reset_index(name='nb_palyers').sort_values(by='nb_palyers', ascending=False)

player_by_country

                   country     platform  nb_palyers
319                 unknow         xbox      274450
318                 unknow        steam      177868
302          United States  playstation       81264
267                  Spain  playstation       34724
300         United Kingdom  playstation       32149
..                     ...          ...         ...
179             Mauritania        steam          10
170                 Malawi        steam           9
161                Lesotho        steam           9
189             Montserrat        steam           9
247  Sao Tome and Principe        steam           8

[321 rows x 3 columns]

In [ ]:
players_history = pd.merge(left=df_players, right=df_history, on='playerid', how='inner')
players_history

,playerid,country,platform_x,created,created_date,created_time,achievementid,date_acquired,platform_y,date_acquired_date,date_acquired_time
0,2744567_playstation,Croatia,playstation,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
1,328452_playstation,United States,playstation,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
2,2521482_playstation,United Kingdom,playstation,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
3,390175_playstation,"Korea, Republic of",playstation,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
4,4348945_playstation,Russian Federation,playstation,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
46520768,1773447_xbox,unknow,xbox,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
46520769,1934243_xbox,unknow,xbox,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
46520770,2140366_xbox,unknow,xbox,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
46520771,2231830_xbox,unknow,xbox,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN
46520772,2526457_xbox,unknow,xbox,unknow,unknown,unknown,NaN,NaT,NaN,NaN,NaN